#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(763, 621)
        Dialog.setStyleSheet("background: #fffff;")
        self.gridLayout_2 = QtWidgets.QGridLayout(Dialog)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.gridLayout.setVerticalSpacing(4)
        self.gridLayout.setObjectName("gridLayout")
        self.frame = QtWidgets.QFrame(Dialog)
        self.frame.setStyleSheet("    QFrame {\n"
"        background-color: #1e1e1e;\n"
"        border: 1px solid #333;\n"
"        border-radius: 8px;\n"
"        padding: 15px;\n"
"    }")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.frame)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.tableWidget = QtWidgets.QTableWidget(self.frame)
        self.tableWidget.setMinimumSize(QtCore.QSize(220, 400))
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.tableWidget.setFont(font)
        self.tableWidget.setMouseTracking(False)
        self.tableWidget.setStyleSheet("    QTableWidget {\n"
"        background-color: white;\n"
"        gridline-color: #e0e0e0;\n"
"        font-size: 13px;\n"
"        selection-background-color: #e6f7ff;\n"
"        selection-color: #0056b3;\n"
"    }\n"
"    \n"
"    QHeaderView::section {\n"
"        background-color: #4a86e8;\n"
"        color: white;\n"
"        padding: 6px;\n"
"        border: none;\n"
"        font-weight: bold;\n"
"    }\n"
"    \n"
"    QTableWidget::item {\n"
"        padding: 8px;\n"
"    }\n"
"    \n"
"    QTableWidget::item:selected {\n"
"        background-color: #b3d9ff;\n"
"    }\n"
"    \n"
"    QScrollBar:vertical {\n"
"        width: 12px;\n"
"    }")
        self.tableWidget.setShowGrid(True)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.gridLayout_3.addWidget(self.tableWidget, 0, 0, 2, 1)
        self.line = QtWidgets.QFrame(self.frame)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout_3.addWidget(self.line, 0, 1, 2, 1)
        self.label = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.label.setFont(font)
        self.label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label.setStyleSheet("QLabel {\n"
"        background-color: #f9f9f9;\n"
"        color: #333;\n"
"        font-size: 14px;\n"
"        padding: 15px;\n"
"        border: 1px solid #ddd;\n"
"        border-radius: 8px;\n"
"        margin: 10px;\n"
"}")
        self.label.setText("")
        self.label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label.setObjectName("label")
        self.gridLayout_3.addWidget(self.label, 0, 2, 1, 1)
        self.buttonBox = QtWidgets.QDialogButtonBox(self.frame)
        self.buttonBox.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.buttonBox.setStyleSheet("    QDialogButtonBox {\n"
"        background-color: #844ae8;\n"
"        border-top: 1px solid #eee;\n"
"        padding: 10px;\n"
"    }\n"
"    \n"
"    QPushButton {\n"
"        background-color: #964ad1;\n"
"        color: #c57aff;\n"
"        border: none;\n"
"        border-radius: 4px;\n"
"        padding: 8px 16px;\n"
"        min-width: 80px;\n"
"        font-weight: bold;\n"
"    }\n"
"    \n"
"    QPushButton:hover {\n"
"        background-color: #7543cc;\n"
"    }\n"
"    \n"
"    QPushButton:pressed {\n"
"        background-color: #270a5b;\n"
"    }\n"
"    \n"
"    QPushButton:focus {\n"
"        outline: 2px solid #a8c6ff;\n"
"    }\n"
"    ")
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setCenterButtons(True)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout_3.addWidget(self.buttonBox, 1, 2, 1, 1)
        self.gridLayout.addWidget(self.frame, 0, 0, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
