# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\Armin\Documents\Code\Python\Portfolio\visual photo\data\window.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from pathlib import Path
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import QCoreApplication

def style_reader(paths):
    full_stylesheet = ""
    for path in paths:
        try:
            with open(Path(rf"source/styles/{path}").absolute(), "r") as f:
                full_stylesheet = full_stylesheet + f.read()

        except FileNotFoundError:
            pass
            # TODO: add error handler
    return full_stylesheet

style_paths = ["check_box_style.qss", "radio_button_style.qss", "combo_box_style.qss"]


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        stylesheet = style_reader(style_paths)

        MainWindow.setStyleSheet(stylesheet)

        MainWindow.setWindowTitle("Visual Photo")
        MainWindow.resize(655, 662)

        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setMaximumSize(QtCore.QSize(1092, 662))
        self.centralwidget.setStyleSheet("")
        self.centralwidget.setObjectName("centralwidget")

        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.gridLayout.setObjectName("gridLayout")

        self.main_grid_layout = QtWidgets.QFrame(self.centralwidget)
        self.main_grid_layout.setMaximumSize(QtCore.QSize(1070, 640))
        self.main_grid_layout.setStyleSheet("background: #1d1c1d;")
        self.main_grid_layout.setObjectName("main_grid_layout")

        self.main_layout = QtWidgets.QGridLayout(self.main_grid_layout)
        self.main_layout.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.main_layout.setObjectName("main_layout")
        self.export_button = QtWidgets.QPushButton(self.main_grid_layout)

        font = QtGui.QFont()
        font.setFamily("Mitra")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)

        self.export_button.setFont(font)

        self.export_button.setStyleSheet("""
            QPushButton{
                background-color: #a822ff;
                border-style: outset;
                border-width: 6px;
                border-radius: 15px;
                border-color: #8e13de;
                min-width: 10em;
                padding: 5px;
                color: #17022c;
            }
            QPushButton:hover { background-color: #901ddb; border-color: #7a0ecc;}
            QPushButton:pressed { background-color: #450e69; border-color: #7a0ecc;}
            QPushButton:disabled {background-color: #382345; border-color: #271c2e;}

        """)

        self.export_button.setObjectName("export_button")
        self.main_layout.addWidget(self.export_button, 9, 4, 1, 2)
        self.copy_files_check = QtWidgets.QCheckBox(self.main_grid_layout)
        self.copy_files_check.setText("copy new files")
        self.copy_files_check.setStyleSheet("size:20;")
        self.copy_files_check.setObjectName("copy_files_check")
        self.main_layout.addWidget(self.copy_files_check, 8, 4, 1, 1)
        self.import_button = QtWidgets.QPushButton(self.main_grid_layout)

        self.import_button.setFont(font)

        self.import_button.setStyleSheet("""
            QPushButton{
                background-color: #a822ff;
                border-style: outset;
                border-width: 6px;
                border-radius: 15px;
                border-color: #8e13de;
                min-width: 10em;
                padding: 5px;
                color: #17022c;
            }
            QPushButton:hover { background-color: #901ddb; border-color: #7a0ecc;}
            QPushButton:pressed { background-color: #450e69; border-color: #7a0ecc;}
            QPushButton:disabled {background-color: #382345; border-color: #271c2e;}

        """)

        self.import_button.setObjectName("import_button")
        self.main_layout.addWidget(self.import_button, 3, 4, 1, 2)
        self.import_setting_fream = QtWidgets.QFrame(self.main_grid_layout)
        self.import_setting_fream.setStyleSheet("background: #222123;\n"
                                                "border-width: 6px;\n"
                                                "border-radius: 15px;\n"
                                                "border-color: #8e13de;")
        self.import_setting_fream.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.import_setting_fream.setFrameShadow(QtWidgets.QFrame.Raised)
        self.import_setting_fream.setObjectName("import_setting_fream")
        self.image_fream_i = QtWidgets.QFrame(self.import_setting_fream)
        self.image_fream_i.setGeometry(QtCore.QRect(10, 10, 151, 41))
        self.image_fream_i.setStyleSheet("background: #38323d;\n"
                                         "border-width: 6px;\n"
                                         "border-radius: 15px;\n"
                                         "border-color: #8e13de;")
        self.image_fream_i.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.image_fream_i.setFrameShadow(QtWidgets.QFrame.Raised)
        self.image_fream_i.setObjectName("image_fream_i")

        self.image_i = QtWidgets.QRadioButton(self.image_fream_i)
        self.image_i.setFont(font)
        self.image_i.setObjectName("image_i")

        self.dir_fream_i = QtWidgets.QFrame(self.import_setting_fream)
        self.dir_fream_i.setGeometry(QtCore.QRect(10, 61, 151, 41))
        self.dir_fream_i.setStyleSheet("background: #38323d;\n"
                                       "border-width: 6px;\n"
                                       "border-radius: 15px;\n"
                                       "border-color: #8e13de;")
        self.dir_fream_i.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.dir_fream_i.setFrameShadow(QtWidgets.QFrame.Raised)
        self.dir_fream_i.setObjectName("dir_fream_i")

        self.dir_i = QtWidgets.QRadioButton(self.dir_fream_i)
        self.dir_i.setFont(font)
        self.dir_i.setObjectName("dir_i")

        self.import_group = QtWidgets.QButtonGroup(self.import_setting_fream)
        self.import_group.addButton(self.image_i)
        self.import_group.addButton(self.dir_i)

        self.main_layout.addWidget(self.import_setting_fream, 4, 4, 2, 2)
        self.num_file_fream = QtWidgets.QFrame(self.main_grid_layout)
        self.num_file_fream.setStyleSheet("background: #222123;\n"
                                          "border-width: 6px;\n"
                                          "border-radius: 15px;\n"
                                          "border-color: #8e13de;")
        self.num_file_fream.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.num_file_fream.setFrameShadow(QtWidgets.QFrame.Raised)
        self.num_file_fream.setObjectName("num_file_fream")

        self.num_file_label = QtWidgets.QLabel(self.num_file_fream)
        self.num_file_label.setGeometry(QtCore.QRect(0, 0, 171, 44))
        self.num_file_label.setFont(font)
        self.num_file_label.setStyleSheet("QLabel {\n"
                                          "        color: #17022c;\n"
                                          "}")
        self.num_file_label.setText("")
        self.num_file_label.setObjectName("num_file_label")
        self.main_layout.addWidget(self.num_file_fream, 7, 4, 1, 2)
        self.path_fream = QtWidgets.QFrame(self.main_grid_layout)
        self.path_fream.setStyleSheet("background: #222123;\n"
                                      "border-width: 6px;\n"
                                      "border-radius: 15px;\n"
                                      "border-color: #8e13de;")
        self.path_fream.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.path_fream.setFrameShadow(QtWidgets.QFrame.Raised)
        self.path_fream.setObjectName("path_fream")
        self.path_label = QtWidgets.QLabel(self.path_fream)
        self.path_label.setGeometry(QtCore.QRect(10, -10, 189, 55))
        self.path_label.setFont(font)
        self.path_label.setStyleSheet("QLabel {\n"
                                      "        color: #17022c;\n"
                                      "}")
        self.path_label.setText("")
        self.path_label.setObjectName("path_label")
        self.main_layout.addWidget(self.path_fream, 6, 4, 1, 2)
        self.input_text_fream = QtWidgets.QFrame(self.main_grid_layout)
        self.input_text_fream.setStyleSheet("background: #222123;\n"
                                            "border-width: 6px;\n"
                                            "border-radius: 15px;\n"
                                            "border-color: #8e13de;")
        self.input_text_fream.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.input_text_fream.setFrameShadow(QtWidgets.QFrame.Raised)
        self.input_text_fream.setObjectName("input_text_fream")

        Input_text_font = QtGui.QFont()
        Input_text_font.setFamily("Mitra")
        Input_text_font.setPointSize(20)
        Input_text_font.setBold(True)
        Input_text_font.setWeight(75)

        self.Input_Label = QtWidgets.QLabel(self.input_text_fream)
        self.Input_Label.move(20, 20)
        self.Input_Label.setBaseSize(40, 20)
        self.Input_Label.setFont(Input_text_font)
        self.Input_Label.setStyleSheet("QLabel {\n"
                                       "        color: #17022c;\n"
                                       "}")
        self.Input_Label.setObjectName("Input_Label")
        self.Input_Label.setSizePolicy(
            QtWidgets.QSizePolicy.MinimumExpanding,
            QtWidgets.QSizePolicy.MinimumExpanding
        )
        self.main_layout.addWidget(self.input_text_fream, 1, 4, 1, 1)
        self.logo_fream1 = QtWidgets.QFrame(self.main_grid_layout)
        self.logo_fream1.setStyleSheet("background: #222123;\n"
                                       "border-width: 6px;\n"
                                       "border-radius: 15px;\n"
                                       "border-color: #8e13de;")
        self.logo_fream1.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.logo_fream1.setFrameShadow(QtWidgets.QFrame.Raised)
        self.logo_fream1.setObjectName("logo_fream1")

        self.gridLayout_2 = QtWidgets.QGridLayout(self.logo_fream1)
        self.gridLayout_2.setObjectName("gridLayout_2")

        self.logo_fream2 = QtWidgets.QFrame(self.logo_fream1)
        self.logo_fream2.setStyleSheet("background: #38323d;\n"
                                       "border-width: 6px;\n"
                                       "border-radius: 15px;\n"
                                       "border-color: #8e13de;")

        self.logo_fream2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.logo_fream2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.logo_fream2.setObjectName("logo_fream2")

        Logofont = QtGui.QFont()
        Logofont.setFamily("Mitra")
        Logofont.setPointSize(20)
        Logofont.setBold(True)
        Logofont.setWeight(75)

        self.VISUAL_PHOTO = QtWidgets.QLabel(self.logo_fream2)
        self.VISUAL_PHOTO.setFont(Logofont)
        self.VISUAL_PHOTO.setStyleSheet("QLabel {\n"
                                        "    color: #17022c;\n"
                                        "}")
        self.VISUAL_PHOTO.setObjectName("VISUAL_PHOTO")
        self.VISUAL_PHOTO.move(20, 10)

        self.gridLayout_2.addWidget(self.logo_fream2, 0, 0, 1, 1)
        self.main_layout.addWidget(self.logo_fream1, 1, 1, 1, 2)

        self.buttons_frame = QtWidgets.QFrame(self.main_grid_layout)
        self.buttons_frame.setStyleSheet("background: #222123;\n"
                                         "border-width: 6px;\n"
                                         "border-radius: 60px;\n"
                                         "border-color: #8e13de;")
        self.buttons_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.buttons_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.buttons_frame.setObjectName("buttons_frame")

        self.gridLayout_3 = QtWidgets.QGridLayout(self.buttons_frame)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.oil_b = QtWidgets.QPushButton(self.buttons_frame)

        self.oil_b.setFont(font)
        self.oil_b.setStyleSheet("QPushButton {\n"
                                 "   \n"
                                 "    background: qlineargradient(x1:0, y1:0, x2:0, y2:1,\n"
                                 "                                stop:0 #790cea, stop:1 #4d0cea);\n"
                                 "    \n"
                                 "  \n"
                                 "    border: 6px solid #4310bd;\n"
                                 "    border-radius: 15px;\n"
                                 "    outline: 2px solid rgba(255, 255, 255, 0.4);\n"
                                 "    box-shadow: inset 0 0 12px rgba(0, 0, 0, 0.6), \n"
                                 "                0 4px 8px rgba(0, 0, 0, 0.4);\n"
                                 "    \n"
                                 " \n"
                                 "    color: #17022c;\n"
                                 "    min-width: 10em;\n"
                                 "    padding: 8px 16px;\n"
                                 "}\n"
                                 "\n"
                                 "QPushButton:hover {\n"
                                 " \n"
                                 "    background: qlineargradient(x1:0, y1:0, x2:0, y2:1,\n"
                                 "                                stop:0 #7f23ef, stop:1 #0303f1);\n"
                                 "    border-color: #501dcb;\n"
                                 "    box-shadow: inset 0 0 15px rgba(0, 0, 0, 0.8), \n"
                                 "                0 6px 12px rgba(0, 0, 0, 0.5);\n"
                                 "}\n"
                                 "\n"
                                 "QPushButton:pressed {\n"
                                 "   \n"
                                 "    background: qlineargradient(x1:0, y1:0, x2:0, y2:1,\n"
                                 "                                stop:0 #9b1fe0, stop:1 #7e0dc7);\n"
                                 "    border-color: #7a0fc0;\n"
                                 "    padding: 10px 16px 6px 16px;\n"
                                 "    box-shadow: inset 0 0 20px rgba(0, 0, 0, 0.9), \n"
                                 "                0 2px 4px rgba(0, 0, 0, 0.3);\n"
                                 "}")
        self.oil_b.setObjectName("oil_b")
        self.gridLayout_3.addWidget(self.oil_b, 0, 2, 1, 1)
        self.glow_b = QtWidgets.QPushButton(self.buttons_frame)
        self.glow_b.setFont(font)
        self.glow_b.setStyleSheet("QPushButton {\n"
                                  "   \n"
                                  "    background: qlineargradient(x1:0, y1:0, x2:0, y2:1,\n"
                                  "                                stop:0 #790cea, stop:1 #4d0cea);\n"
                                  "    \n"
                                  "  \n"
                                  "    border: 6px solid #4310bd;\n"
                                  "    border-radius: 15px;\n"
                                  "    outline: 2px solid rgba(255, 255, 255, 0.4);\n"
                                  "    box-shadow: inset 0 0 12px rgba(0, 0, 0, 0.6), \n"
                                  "                0 4px 8px rgba(0, 0, 0, 0.4);\n"
                                  "    \n"
                                  " \n"
                                  "    color: #17022c;\n"
                                  "    min-width: 10em;\n"
                                  "    padding: 8px 16px;\n"
                                  "}\n"
                                  "\n"
                                  "QPushButton:hover {\n"
                                  " \n"
                                  "    background: qlineargradient(x1:0, y1:0, x2:0, y2:1,\n"
                                  "                                stop:0 #7f23ef, stop:1 #0303f1);\n"
                                  "    border-color: #501dcb;\n"
                                  "    box-shadow: inset 0 0 15px rgba(0, 0, 0, 0.8), \n"
                                  "                0 6px 12px rgba(0, 0, 0, 0.5);\n"
                                  "}\n"
                                  "\n"
                                  "QPushButton:pressed {\n"
                                  "   \n"
                                  "    background: qlineargradient(x1:0, y1:0, x2:0, y2:1,\n"
                                  "                                stop:0 #9b1fe0, stop:1 #7e0dc7);\n"
                                  "    border-color: #7a0fc0;\n"
                                  "    padding: 10px 16px 6px 16px;\n"
                                  "    box-shadow: inset 0 0 20px rgba(0, 0, 0, 0.9), \n"
                                  "                0 2px 4px rgba(0, 0, 0, 0.3);\n"
                                  "}")
        self.glow_b.setObjectName("glow_b")
        self.gridLayout_3.addWidget(self.glow_b, 1, 2, 1, 1)
        self.vintage_b = QtWidgets.QPushButton(self.buttons_frame)
        self.vintage_b.setFont(font)
        self.vintage_b.setStyleSheet("QPushButton {\n"
                                     "   \n"
                                     "    background: qlineargradient(x1:0, y1:0, x2:0, y2:1,\n"
                                     "                                stop:0 #790cea, stop:1 #4d0cea);\n"
                                     "    \n"
                                     "  \n"
                                     "    border: 6px solid #4310bd;\n"
                                     "    border-radius: 15px;\n"
                                     "    outline: 2px solid rgba(255, 255, 255, 0.4);\n"
                                     "    box-shadow: inset 0 0 12px rgba(0, 0, 0, 0.6), \n"
                                     "                0 4px 8px rgba(0, 0, 0, 0.4);\n"
                                     "    \n"
                                     " \n"
                                     "    color: #17022c;\n"
                                     "    min-width: 10em;\n"
                                     "    padding: 8px 16px;\n"
                                     "}\n"
                                     "\n"
                                     "QPushButton:hover {\n"
                                     " \n"
                                     "    background: qlineargradient(x1:0, y1:0, x2:0, y2:1,\n"
                                     "                                stop:0 #7f23ef, stop:1 #0303f1);\n"
                                     "    border-color: #501dcb;\n"
                                     "    box-shadow: inset 0 0 15px rgba(0, 0, 0, 0.8), \n"
                                     "                0 6px 12px rgba(0, 0, 0, 0.5);\n"
                                     "}\n"
                                     "\n"
                                     "QPushButton:pressed {\n"
                                     "   \n"
                                     "    background: qlineargradient(x1:0, y1:0, x2:0, y2:1,\n"
                                     "                                stop:0 #9b1fe0, stop:1 #7e0dc7);\n"
                                     "    border-color: #7a0fc0;\n"
                                     "    padding: 10px 16px 6px 16px;\n"
                                     "    box-shadow: inset 0 0 20px rgba(0, 0, 0, 0.9), \n"
                                     "                0 2px 4px rgba(0, 0, 0, 0.3);\n"
                                     "}")
        self.vintage_b.setObjectName("vintage_b")
        self.gridLayout_3.addWidget(self.vintage_b, 3, 2, 1, 1)
        self.Blur_b = QtWidgets.QPushButton(self.buttons_frame)
        self.Blur_b.setFont(font)
        self.Blur_b.setStyleSheet("QPushButton {\n"
                                  "   \n"
                                  "    background: qlineargradient(x1:0, y1:0, x2:0, y2:1,\n"
                                  "                                stop:0 #790cea, stop:1 #4d0cea);\n"
                                  "    \n"
                                  "  \n"
                                  "    border: 6px solid #4310bd;\n"
                                  "    border-radius: 15px;\n"
                                  "    outline: 2px solid rgba(255, 255, 255, 0.4);\n"
                                  "    box-shadow: inset 0 0 12px rgba(0, 0, 0, 0.6), \n"
                                  "                0 4px 8px rgba(0, 0, 0, 0.4);\n"
                                  "    \n"
                                  " \n"
                                  "    color: #17022c;\n"
                                  "    min-width: 10em;\n"
                                  "    padding: 8px 16px;\n"
                                  "}\n"
                                  "\n"
                                  "QPushButton:hover {\n"
                                  " \n"
                                  "    background: qlineargradient(x1:0, y1:0, x2:0, y2:1,\n"
                                  "                                stop:0 #7f23ef, stop:1 #0303f1);\n"
                                  "    border-color: #501dcb;\n"
                                  "    box-shadow: inset 0 0 15px rgba(0, 0, 0, 0.8), \n"
                                  "                0 6px 12px rgba(0, 0, 0, 0.5);\n"
                                  "}\n"
                                  "\n"
                                  "QPushButton:pressed {\n"
                                  "   \n"
                                  "    background: qlineargradient(x1:0, y1:0, x2:0, y2:1,\n"
                                  "                                stop:0 #9b1fe0, stop:1 #7e0dc7);\n"
                                  "    border-color: #7a0fc0;\n"
                                  "    padding: 10px 16px 6px 16px;\n"
                                  "    box-shadow: inset 0 0 20px rgba(0, 0, 0, 0.9), \n"
                                  "                0 2px 4px rgba(0, 0, 0, 0.3);\n"
                                  "}")
        self.Blur_b.setObjectName("Blur_b")
        self.gridLayout_3.addWidget(self.Blur_b, 6, 2, 1, 1)
        self.gray_scale_b = QtWidgets.QPushButton(self.buttons_frame)
        self.gray_scale_b.setFont(font)
        self.gray_scale_b.setStyleSheet("QPushButton {\n"
                                        "   \n"
                                        "    background: qlineargradient(x1:0, y1:0, x2:0, y2:1,\n"
                                        "                                stop:0 #790cea, stop:1 #4d0cea);\n"
                                        "    \n"
                                        "  \n"
                                        "    border: 6px solid #4310bd;\n"
                                        "    border-radius: 15px;\n"
                                        "    outline: 2px solid rgba(255, 255, 255, 0.4);\n"
                                        "    box-shadow: inset 0 0 12px rgba(0, 0, 0, 0.6), \n"
                                        "                0 4px 8px rgba(0, 0, 0, 0.4);\n"
                                        "    \n"
                                        " \n"
                                        "    color: #17022c;\n"
                                        "    min-width: 10em;\n"
                                        "    padding: 8px 16px;\n"
                                        "}\n"
                                        "\n"
                                        "QPushButton:hover {\n"
                                        " \n"
                                        "    background: qlineargradient(x1:0, y1:0, x2:0, y2:1,\n"
                                        "                                stop:0 #7f23ef, stop:1 #0303f1);\n"
                                        "    border-color: #501dcb;\n"
                                        "    box-shadow: inset 0 0 15px rgba(0, 0, 0, 0.8), \n"
                                        "                0 6px 12px rgba(0, 0, 0, 0.5);\n"
                                        "}\n"
                                        "\n"
                                        "QPushButton:pressed {\n"
                                        "   \n"
                                        "    background: qlineargradient(x1:0, y1:0, x2:0, y2:1,\n"
                                        "                                stop:0 #9b1fe0, stop:1 #7e0dc7);\n"
                                        "    border-color: #7a0fc0;\n"
                                        "    padding: 10px 16px 6px 16px;\n"
                                        "    box-shadow: inset 0 0 20px rgba(0, 0, 0, 0.9), \n"
                                        "                0 2px 4px rgba(0, 0, 0, 0.3);\n"
                                        "}")
        self.gray_scale_b.setObjectName("gray_scale_b")
        self.gridLayout_3.addWidget(self.gray_scale_b, 5, 2, 1, 1)
        self.negate_b = QtWidgets.QPushButton(self.buttons_frame)
        self.negate_b.setFont(font)
        self.negate_b.setStyleSheet("QPushButton {\n"
                                    "   \n"
                                    "    background: qlineargradient(x1:0, y1:0, x2:0, y2:1,\n"
                                    "                                stop:0 #790cea, stop:1 #4d0cea);\n"
                                    "    \n"
                                    "  \n"
                                    "    border: 6px solid #4310bd;\n"
                                    "    border-radius: 15px;\n"
                                    "    outline: 2px solid rgba(255, 255, 255, 0.4);\n"
                                    "    box-shadow: inset 0 0 12px rgba(0, 0, 0, 0.6), \n"
                                    "                0 4px 8px rgba(0, 0, 0, 0.4);\n"
                                    "    \n"
                                    " \n"
                                    "    color: #17022c;\n"
                                    "    min-width: 10em;\n"
                                    "    padding: 8px 16px;\n"
                                    "}\n"
                                    "\n"
                                    "QPushButton:hover {\n"
                                    " \n"
                                    "    background: qlineargradient(x1:0, y1:0, x2:0, y2:1,\n"
                                    "                                stop:0 #7f23ef, stop:1 #0303f1);\n"
                                    "    border-color: #501dcb;\n"
                                    "    box-shadow: inset 0 0 15px rgba(0, 0, 0, 0.8), \n"
                                    "                0 6px 12px rgba(0, 0, 0, 0.5);\n"
                                    "}\n"
                                    "\n"
                                    "QPushButton:pressed {\n"
                                    "   \n"
                                    "    background: qlineargradient(x1:0, y1:0, x2:0, y2:1,\n"
                                    "                                stop:0 #9b1fe0, stop:1 #7e0dc7);\n"
                                    "    border-color: #7a0fc0;\n"
                                    "    padding: 10px 16px 6px 16px;\n"
                                    "    box-shadow: inset 0 0 20px rgba(0, 0, 0, 0.9), \n"
                                    "                0 2px 4px rgba(0, 0, 0, 0.3);\n"
                                    "}")
        self.negate_b.setObjectName("negate_b")
        self.gridLayout_3.addWidget(self.negate_b, 4, 2, 1, 1)
        self.mosaic_b = QtWidgets.QPushButton(self.buttons_frame)
        self.mosaic_b.setFont(font)
        self.mosaic_b.setStyleSheet("QPushButton {\n"
                                    "   \n"
                                    "    background: qlineargradient(x1:0, y1:0, x2:0, y2:1,\n"
                                    "                                stop:0 #790cea, stop:1 #4d0cea);\n"
                                    "    \n"
                                    "  \n"
                                    "    border: 6px solid #4310bd;\n"
                                    "    border-radius: 15px;\n"
                                    "    outline: 2px solid rgba(255, 255, 255, 0.4);\n"
                                    "    box-shadow: inset 0 0 12px rgba(0, 0, 0, 0.6), \n"
                                    "                0 4px 8px rgba(0, 0, 0, 0.4);\n"
                                    "    \n"
                                    " \n"
                                    "    color: #17022c;\n"
                                    "    min-width: 10em;\n"
                                    "    padding: 8px 16px;\n"
                                    "}\n"
                                    "\n"
                                    "QPushButton:hover {\n"
                                    " \n"
                                    "    background: qlineargradient(x1:0, y1:0, x2:0, y2:1,\n"
                                    "                                stop:0 #7f23ef, stop:1 #0303f1);\n"
                                    "    border-color: #501dcb;\n"
                                    "    box-shadow: inset 0 0 15px rgba(0, 0, 0, 0.8), \n"
                                    "                0 6px 12px rgba(0, 0, 0, 0.5);\n"
                                    "}\n"
                                    "\n"
                                    "QPushButton:pressed {\n"
                                    "   \n"
                                    "    background: qlineargradient(x1:0, y1:0, x2:0, y2:1,\n"
                                    "                                stop:0 #9b1fe0, stop:1 #7e0dc7);\n"
                                    "    border-color: #7a0fc0;\n"
                                    "    padding: 10px 16px 6px 16px;\n"
                                    "    box-shadow: inset 0 0 20px rgba(0, 0, 0, 0.9), \n"
                                    "                0 2px 4px rgba(0, 0, 0, 0.3);\n"
                                    "}")
        self.mosaic_b.setObjectName("mosaic_b")
        self.gridLayout_3.addWidget(self.mosaic_b, 2, 2, 1, 1)
        self.main_layout.addWidget(self.buttons_frame, 2, 1, 8, 1)
        self.gridLayout.addWidget(self.main_grid_layout, 1, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        translator = QCoreApplication.translate

        system_language = QtCore.QLocale.system().name()

        MainWindow.setWindowTitle(translator("MainWindow", "Visual Photo"))
        self.export_button.setText(translator("button", "Export"))
        self.copy_files_check.setText(translator("MainWindow", "copy new files"))
        self.import_button.setText(translator("button", "import"))
        self.image_i.setText(translator("radio box", "a image"))
        self.dir_i.setText(translator("radio box", "a directory"))
        self.Input_Label.setText(translator("text", "Input"))
        self.VISUAL_PHOTO.setText(translator("Logo text", "VISUAL PHOTO"))
        self.oil_b.setText(translator("effect button", "Oil Painting"))
        self.glow_b.setText(translator("effect button", "Glow"))
        self.vintage_b.setText(translator("effect button", "Vintage"))
        self.Blur_b.setText(translator("effect button", "Blur"))
        self.gray_scale_b.setText(translator("effect button", "Gray Scale"))
        self.negate_b.setText(translator("effect button", "Negate"))
        self.mosaic_b.setText(translator("effect button", "Mosaic"))

        MainWindow.show()
